# chạy một lần để khởi tạo môi trường

In [2]:
!git clone https://github.com/telexyz/lyric-align.git
%cd lyric-align
!pip install -r requirements.txt
# !apt install ffmpeg lame sox

Cloning into 'lyric-align'...
remote: Enumerating objects: 3812, done.
remote: Counting objects: 100% (144/144), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 3812 (delta 50), reused 118 (delta 26), pack-reused 3668
Receiving objects: 100% (3812/3812), 101.81 MiB | 37.87 MiB/s, done.
Resolving deltas: 100% (53/53), done.
/content/lyric-align
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 3.1 MB 5.0 MB/s 
     |████████████████████████████████| 180 kB 64.3 MB/s 
  Created wheel for distance: filename=Distance-0.1.3-py3-none-any.whl size=16289 sha256=8217a54096fe8489754862e2e95650501659ad96431d050d19d397b693570e26
  Stored in directory: /root/.cache/pip/wheels/b2/10/1b/96fca621a1be378e2fe104cfb0d160bb6cdf3d04a3d35266cc
Successfully built distance




# Load Vietnamese Songs Datasets


In [3]:
# !git pull
from data import SongsDataset
val_data = SongsDataset("validate")
print(val_data[0])
len(val_data)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.


(array([[ 0.0000000e+00, -3.0517578e-05,  0.0000000e+00, ...,
        -6.1035156e-05,  1.2207031e-04, -1.5258789e-04]], dtype=float32), None, None, array([ 34,  27,  35,   0,  29,  41,  40,   0,  46,  34,  88,  40,   0,
        38,  88,  40,   0,  29,  41,  40,   0,  71,  67,  27,   0,  40,
        34,  27,  47,   0,  29,  87,  40,   0,  40,  34,  27,  47,   0,
        71, 116,  46,   0,  71,  47,  65,  35,   0,  29,  34,  27,   0,
        46,  34,  88,  40,   0,  38,  88,  40,   0,  28,  47, 105,  40,
         0,  46,  34,  35,  47,   0,  33, 102,  35,   0,  29,  34,  68,
        40,  33,   0,  71,  95,  40,   0,  39, 109,  35,   0,  39,  87,
        40,  33,   0,  29,  34,  41]), None)


120

In [3]:
train_data = SongsDataset("train")
print(train_data[0])
len(train_data)

(array([[ 0.0000000e+00, -3.0517578e-05,  0.0000000e+00, ...,
        -5.1879883e-04,  1.8310547e-04,  2.1362305e-04]], dtype=float32), None, None, ['n', 'g', 'ư', 'ờ', 'i', ' ', 'ở', ' ', 'đ', 'ó', ' ', 'a', 'n', 'h', ' ', 'ở', ' ', 'đ', 'â', 'y', ' ', 'm', 'à', ' ', 's', 'a', 'o', ' ', 't', 'r', 'á', 'i', ' ', 't', 'i', 'm', ' ', 'a', 'n', 'h', ' ', 'l', 'ạ', 'n', 'h', ' ', 'q', 'u', 'á', ' ', 'c', 'ũ', 'n', 'g', ' ', 'c', 'h', 'ỉ', ' ', 'l', 'à', ' ', 'd', 'o', ' ', 'k', 'h', 'o', 'ả', 'n', 'g', ' ', 'c', 'á', 'c', 'h', ' ', 'k', 'h', 'i', 'ế', 'n', ' ', 't', 'a', ' ', 'v', 'ô', ' ', 't', 'ì', 'n', 'h', ' ', 'l', 'ạ', 'c', ' ', 'm', 'ấ', 't', ' ', 'n', 'h', 'a', 'u', ' ', 'y', 'ê', 'u', ' ', 'x', 'a', ' ', 'k', 'h', 'ó', ' ', 'l', 'ắ', 'm', ' ', 'n', 'h', 'ớ', ' ', 't', 'h', 'ư', 'ơ', 'n', 'g', ' ', 'm', 'à', ' ', 'l', 'à', 'm', ' ', 't', 'r', 'á', 'i', ' ', 't', 'i', 'm', ' ', 'đ', 'a', 'u', ' ', 'm', 'ì', 'n', 'h', ' ', 'đ', 'ã', ' ', 'h', 'ứ', 'a', ' ', 's', 'ẽ', ' ', 'c', 'ù', '

800

In [4]:
import torch
import torchaudio

from model import data_processing
data = train_data[0]
from model import train_audio_transforms

for (waveform, _, _, phone, _) in [data]:
    waveform = torch.Tensor(waveform)
    spec = train_audio_transforms(waveform).squeeze(0).transpose(0, 1)
    print(spec, phone)

tensor([[0.0000e+00, 5.5523e-11, 1.5058e-10,  ..., 6.5165e-09, 3.8553e-08,
         4.9053e-08],
        [0.0000e+00, 9.0561e-06, 2.4560e-05,  ..., 1.3755e-07, 8.6429e-08,
         2.6156e-07],
        [0.0000e+00, 5.4379e-05, 1.4747e-04,  ..., 9.4668e-08, 8.9190e-08,
         8.5501e-08],
        ...,
        [0.0000e+00, 2.1553e-04, 5.8450e-04,  ..., 3.8551e-07, 1.2415e-07,
         1.7081e-07],
        [0.0000e+00, 1.2451e-04, 3.3768e-04,  ..., 1.3796e-07, 2.2452e-07,
         2.2233e-07],
        [0.0000e+00, 1.3839e-03, 3.7530e-03,  ..., 2.3102e-07, 7.6060e-07,
         1.0569e-06]]) ['n', 'g', 'ư', 'ờ', 'i', ' ', 'ở', ' ', 'đ', 'ó', ' ', 'a', 'n', 'h', ' ', 'ở', ' ', 'đ', 'â', 'y', ' ', 'm', 'à', ' ', 's', 'a', 'o', ' ', 't', 'r', 'á', 'i', ' ', 't', 'i', 'm', ' ', 'a', 'n', 'h', ' ', 'l', 'ạ', 'n', 'h', ' ', 'q', 'u', 'á', ' ', 'c', 'ũ', 'n', 'g', ' ', 'c', 'h', 'ỉ', ' ', 'l', 'à', ' ', 'd', 'o', ' ', 'k', 'h', 'o', 'ả', 'n', 'g', ' ', 'c', 'á', 'c', 'h', ' ', 'k', 'h', 'i', 'ế'

In [ ]:
!git pull
!mkdir -p checkpoints temp
!python train.py --checkpoint_dir=checkpoints --log_dir=temp --cuda

Already up to date.
Namespace(batch_size=16, checkpoint_dir='checkpoints', cnn_layers=1, cuda=True, dummy=False, load_model=None, log_dir='temp', loss_w=0.1, lr=0.0001, model='baseline', num_workers=1, rnn_dim=256, sr=22050)
cuda
AcousticModel(
  (cnn_layers): Sequential(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
  )
  (rescnn_layers): Sequential(
    (0): ResidualCNN(
      (cnn1): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (cnn2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (dropout1): Dropout(p=0.1, inplace=False)
      (dropout2): Dropout(p=0.1, inplace=False)
      (layer_norm1): CNNLayerNorm(
        (layer_norm): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      )
      (layer_norm2): CNNLayerNorm(
        (layer_norm): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      )
    )
  )
  (maxpooling): MaxPool2d(kernel_size=(2, 3), stride=(2, 3), padding=0, dila